{
 "title": "Aerospike JMS Outbound Summary",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster_name",
    "label": "Cluster Name",
    "query": {
     "query": "label_values(aerospike_jms_outbound_requests, cluster_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total Success Rate/Second",
   "type": "graph",
   "description": "Total incoming XDR records successfully handled.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(aerospike_jms_outbound_requests{cluster_name=\"$cluster_name\",status=\"success\"}[40s]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Total Error Rate/Second",
   "type": "graph",
   "description": "Total incoming XDR records processing error.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(aerospike_jms_outbound_requests{cluster_name=\"$cluster_name\",status=\"error\"}[40s]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Total Skip Rate/Second",
   "type": "graph",
   "description": "Total incoming XDR records skipped.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(aerospike_jms_outbound_requests{cluster_name=\"$cluster_name\",status=\"skipped\"}[40s]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Total Parse Error Rate/Second",
   "type": "graph",
   "description": "Total incoming XDR record parsing error.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(aerospike_jms_outbound_requests{cluster_name=\"$cluster_name\",status=\"parse-error\"}[40s]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "XDR to Connector Lag",
   "type": "graph",
   "description": "Maximum lag in record LUT (last update time) in Aerospike and the record reaching the connectors.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "max(aerospike_jms_outbound_requests_lag{cluster_name=\"$cluster_name\"})",
     "legendFormat": "Maximum Lag"
    }
   ]
  },
  {
   "title": "XDR Connections Rate/Second",
   "type": "graph",
   "description": "Rate of Connections from Aerospike XDR to the connectors.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum  ( \n    rate(aerospike_jms_outbound_connections{cluster_name=\"$cluster_name\"}[40s])\n)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "JMS Connections Rate/Second",
   "type": "graph",
   "description": "Total rate of JMS connections creation.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum ( \n    rate(aerospike_jms_outbound_jms_connections{cluster_name=\"$cluster_name\"}[40s])\n)",
     "legendFormat": "Total"
    }
   ]
  }
 ]
}