/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.aerospike;


public class LibraryTest {
    public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();

    }
}
