/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.aerospike.module2;


public class LibraryTest {
    public void testSomeLibraryMethod() {
        final Library classUnderTest = new Library();

    }
}
